name: gidosa-frontend-webapp prod

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
    #   types: [closed]
    paths-ignore:
      - '.github/workflows/deploy-dev-gidosa-frontend-webapp.yml'
      # - 'public/**'
  workflow_dispatch:
  #   # inputs:
  #   #   region:
  #   #     required: false
  #   #     type: string
  #   #   env:
  #   #     required: true
  #   #     type: string

# env:
#   FILE_STORAGE_BUCKET_DEPLOY_NAME: ${{ secrets.CLOUD_STORAGE_BUCKET_DEPLOY_NAME }}
#   FILE_STORAGE_DEPLOY_FOLDER: ${{ secrets.CLOUD_STORAGE_FOLDER_PROD_WEBAPP }}
#   CODE_DEPLOY_APPLICATION_NAME: ${{ secrets.GCP_CODEDEPLOY_NAME }}
#   CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: ${{ secrets.GCP_GROUP_NAME_PROD_WEBAPP }}

jobs:
  # 의존성 빌드 테스트
  build-codedeploy:
    # environment: dev
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3