name: gidosa-frontend-webapp dev

on:
  push:
    branches: [dev]
  pull_request:
    branches:
      - dev
    #   types: [closed]
    paths-ignore:
      - '.github/workflows/deploy-prod-gidosa-frontend-webapp.yml'
      # - 'public/**'
  workflow_dispatch:
  #   # inputs:
  #   #   region:
  #   #     required: false
  #   #     type: string
  #   #   env:
  #   #     required: true
  #   #     type: string

# env:
#   FILE_STORAGE_BUCKET_DEPLOY_NAME: ${{ secrets.CLOUD_STORAGE_BUCKET_DEPLOY_NAME }}
#   FILE_STORAGE_DEPLOY_FOLDER: ${{ secrets.CLOUD_STORAGE_FOLDER_PROD_WEBAPP }}
#   CODE_DEPLOY_APPLICATION_NAME: ${{ secrets.GCP_CODEDEPLOY_NAME }}
#   CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: ${{ secrets.GCP_GROUP_NAME_PROD_WEBAPP }}

jobs:
  # 의존성 빌드 테스트
  build-deploy:
    # environment: dev
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }} 
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # script: |
          #     cd ${{ github.event.repository.name }}
          #     pwd
          #     sh deploy-ssh.sh  
          script: |
              #source ~/.bashrc
              ln -s /home/ai_safety_system/.nvm/versions/node/v20.18.2/bin/node /usr/local/bin/node
              cd ~/apps-gidosa_net/gidosa-frontend-webapp
              npm install
              npm run build
              # /home/ai_safety_system/.nvm/versions/node/v20.18.2/bin/npm install
              # /home/ai_safety_system/.nvm/versions/node/v20.18.2/bin/npm run build
